### ISSUE TITLE
Sometime freezing

### ISSUE THREAD

**Issue by nicatmanaf** [E-Haci/chrome-os-azerbaijani-keyboard#1]
Can you update that project? Sometimes freezing and keys like ə ö ğ ç ş not responding.

I am using Samsung Chrombook Plus

**Comment by E-Haci** [comment]
1. How often does it happen? 
2. I don't know the reason yet, but when it freezes, just press Alt+Tab and re-switch back to your current tab, it will be reloaded and work ok.
